import { copyFile } from 'node:fs/promises';
import { build } from 'esbuild';

await build({
  entryPoints: ['src/index.mjs'],
  outfile: 'dist/index.mjs',
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'esm',
  banner: {
    js:
      '// Generated by npm run build. YAML license: ./yaml-LICENSE\n' +
      "import { createRequire } from 'node:module';\n" +
      'const require = createRequire(import.meta.url);',
  },
});
await copyFile('node_modules/yaml/LICENSE', 'dist/yaml-LICENSE');
